server:
    port: 8083
    servlet:
        contextPath: /
    error:
        whitelabel:
            enabled: true

## Actuator endpoints
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        beans:
            id: springbeans
            sensitive: false
            enabled: true