# ===================================================================
# COMMON SPRING BOOT PROPERTIES
#
# This sample file is provided as a guideline. Do NOT copy it in its
# entirety to your own application.               ^^^
# ===================================================================
# From https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

debug: false # Enable debug logs.
trace: false # Enable trace logs.

server:
    port: 8083
    servlet:
        contextPath: /
    error:
        whitelabel:
            enabled: true

## Actuator endpoints
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        beans:
            id: springbeans
            sensitive: false
            enabled: true

spring:
    application:
        name: "MY-MICROSERVICE"
    devtools:
        livereload:
            enabled: false
